  // 8 大體系(reserved_1 已啟用為 subscription,reserved_2 保留)
window.PAYMENT_CATEGORIES = [
  { id: "credit_card", name_zh: "信用卡", name_en: "Credit Card", icon: "./assest/payments/icons/credit_card.svg" },
  { id: "ewallet", name_zh: "電子/行動支付", name_en: "E-Wallet / Mobile", icon: "./assest/payments/icons/ewallet.svg" },
  { id: "bank_transfer", name_zh: "銀行轉帳", name_en: "Bank Transfer", icon: "./assest/payments/icons/bank_transfer.svg" },
  { id: "carrier_billing", name_zh: "電信帳單繳費", name_en: "Carrier Billing", icon: "./assest/payments/icons/mobile_phone.svg" },
  { id: "cash_store", name_zh: "實體商店繳費", name_en: "Pay in Store", icon: "./assest/payments/icons/over_the_counter.svg" },
  { id: "bnpl", name_zh: "先買後付", name_en: "BNPL", icon: "./assest/payments/icons/BNPL03.svg" },
  { id: "subscription", name_zh: "訂閱服務", name_en: "Subscription", icon: "./assest/payments/icons/subscription.svg" },
  { id: "reserved_2", name_zh: "（保留）", name_en: "Reserved 2", icon: "./assest/payments/icons/reserved.svg" },
];

  // 各體系底下可用的「支付廠商/方式」清單(2026-06-12 dedup 完成)
window.PAYMENT_METHODS = {
  credit_card: [
    { id: "visa", name_zh: "Visa", name_en: "Visa", icon: "./assest/payments/vendor/credit_card/visa.svg" },
    { id: "mastercard", name_zh: "萬事達", name_en: "Mastercard", icon: "./assest/payments/vendor/credit_card/mastercard.svg" },
    { id: "jcb", name_zh: "JCB", name_en: "JCB", icon: "./assest/payments/vendor/credit_card/jcb.svg" },
    { id: "union_pay", name_zh: "銀聯", name_en: "UnionPay", icon: "./assest/payments/vendor/credit_card/union_pay.svg" },
    { id: "paypal_card", name_zh: "PayPal", name_en: "PayPal", icon: "./assest/payments/vendor/ewallet/paypal_card.svg" },
    { id: "_placeholder_credit_card_1", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/credit_card/_placeholder_credit_card_1.svg" },
    { id: "_placeholder_credit_card_2", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/credit_card/_placeholder_credit_card_2.svg" },
  ],
  ewallet: [
    { id: "line_pay", name_zh: "LINE Pay", name_en: "LINE Pay", icon: "./assest/payments/vendor/ewallet/line_pay.svg" },
    { id: "jko_pay", name_zh: "街口支付", name_en: "JKOPay", icon: "./assest/payments/vendor/ewallet/jko_pay.svg" },
    { id: "taiwan_pay", name_zh: "台灣Pay", name_en: "TaiwanPay", icon: "./assest/payments/vendor/ewallet/taiwan_pay.png" },
    { id: "easy_wallet", name_zh: "悠遊付", name_en: "Easy Wallet", icon: "./assest/payments/vendor/ewallet/easy_wallet.png" },
    { id: "apple_pay", name_zh: "Apple Pay", name_en: "Apple Pay", icon: "./assest/payments/vendor/ewallet/apple_pay.svg" },
    { id: "google_pay", name_zh: "Google Pay", name_en: "Google Pay", icon: "./assest/payments/vendor/ewallet/google_pay.svg" },
    { id: "samsung_pay", name_zh: "Samsung Pay", name_en: "Samsung Pay", icon: "./assest/payments/vendor/ewallet/samsung_pay.svg" },
    { id: "paypal", name_zh: "PayPal", name_en: "PayPal", icon: "./assest/payments/vendor/ewallet/paypal.svg" },
    { id: "alipay", name_zh: "支付寶", name_en: "Alipay", icon: "./assest/payments/vendor/ewallet/alipay.svg" },
    { id: "wechat_pay", name_zh: "微信支付", name_en: "WeChat Pay", icon: "./assest/payments/vendor/ewallet/wechat_pay.svg" },
    { id: "alipayhk", name_zh: "支付寶香港", name_en: "AlipayHK", icon: "./assest/payments/vendor/ewallet/alipayhk.svg" },
    { id: "payme", name_zh: "PayMe", name_en: "PayMe", icon: "./assest/payments/vendor/ewallet/payme.svg" },
    { id: "octopus", name_zh: "八達通", name_en: "Octopus Online Payment", icon: "./assest/payments/vendor/ewallet/octopus.svg" },
    { id: "ovo", name_zh: "OVO", name_en: "OVo", icon: "./assest/payments/vendor/ewallet/ovo.svg" },
    { id: "gopay", name_zh: "GO Pay", name_en: "GO Pay", icon: "./assest/payments/vendor/ewallet/gopay.svg" },
    { id: "dana", name_zh: "DANA", name_en: "DANA", icon: "./assest/payments/vendor/ewallet/dana.svg" },
    { id: "linkaja", name_zh: "LinkAja", name_en: "LinkAja", icon: "./assest/payments/vendor/ewallet/linkaja.svg" },
    { id: "doku", name_zh: "Doku Wallet", name_en: "Doku Wallet", icon: "./assest/payments/vendor/ewallet/doku.svg" },
    { id: "grab_pay", name_zh: "GrabPay", name_en: "GrabPay", icon: "./assest/payments/vendor/ewallet/grab_pay.svg" },
    { id: "shopee_pay", name_zh: "ShopeePay", name_en: "ShopeePay", icon: "./assest/payments/vendor/ewallet/shopee_pay.svg" },
    { id: "touchgo_ewallet", name_zh: "Touch'n Go eWallet", name_en: "Touch'n Go eWallet", icon: "./assest/payments/vendor/ewallet/touchgo_ewallet.svg" },
    { id: "boost_my", name_zh: "Boost", name_en: "Boost", icon: "./assest/payments/vendor/ewallet/boost_my.svg" },
    { id: "paynow", name_zh: "PayNow", name_en: "PayNow", icon: "./assest/payments/vendor/ewallet/paynow.png" },
    { id: "so_cash", name_zh: "SoCash", name_en: "SoCash", icon: "./assest/payments/vendor/ewallet/so_cash.png" },
    { id: "_placeholder_ewallet_1", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/ewallet/_placeholder_ewallet_1.svg" },
    { id: "_placeholder_ewallet_2", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/ewallet/_placeholder_ewallet_2.svg" },
    { id: "pxpay_plus", name_zh: "全支付", name_en: "PXPay Plus", icon: "./assest/payments/vendor/ewallet/pxpay_plus.svg" },
    { id: "pi_app", name_zh: "Pi 拍錢包", name_en: "Pi APP", icon: "./assest/payments/vendor/ewallet/pi_app.svg" },
    { id: "plus_pay", name_zh: "全盈+PAY", name_en: "PlusPay", icon: "./assest/payments/vendor/ewallet/plus_pay.svg" },
    { id: "ez_pay", name_zh: "ezPay簡單付", name_en: "ezPay", icon: "./assest/payments/vendor/ewallet/ez_pay.svg" },
    { id: "i_pass_money", name_zh: "iPASS MONEY", name_en: "iPASS MONEY", icon: "./assest/payments/vendor/ewallet/i_pass_money.svg" },
    { id: "icash_pay", name_zh: "icash Pay", name_en: "icash Pay", icon: "./assest/payments/vendor/ewallet/icash_pay.svg" },
    { id: "qris", name_zh: "QRIS", name_en: "QRIS", icon: "./assest/payments/vendor/ewallet/qris.svg" },
    { id: "sakuku", name_zh: "Sakuku", name_en: "Sakuku", icon: "./assest/payments/vendor/ewallet/sakuku.svg" },
    { id: "bitcoin_ethereum_tether", name_zh: "Bitcoin/Ethereum/Tether", name_en: "Bitcoin/Ethereum/Tether", icon: "./assest/payments/vendor/ewallet/bitcoin_ethereum_tether.svg" },
    { id: "coins_ph", name_zh: "Coins.ph", name_en: "Coins.ph", icon: "./assest/payments/vendor/ewallet/coins_ph.svg" },
    { id: "gcash", name_zh: "Gcash", name_en: "Gcash", icon: "./assest/payments/vendor/ewallet/gcash.svg" },
    { id: "moneygment", name_zh: "Moneygment", name_en: "Moneygment", icon: "./assest/payments/vendor/ewallet/moneygment.svg" },
    { id: "paymaya", name_zh: "Paymaya", name_en: "Paymaya", icon: "./assest/payments/vendor/ewallet/paymaya.svg" },
    { id: "rabbit_line_pay_th", name_zh: "LINE Pay", name_en: "LINE Pay", icon: "./assest/payments/vendor/ewallet/rabbit_line_pay_th.svg" },
    { id: "truemoney", name_zh: "TrueMoney", name_en: "TrueMoney", icon: "./assest/payments/vendor/ewallet/truemoney.svg" },
    { id: "nine_pay", name_zh: "9Pay", name_en: "9Pay", icon: "./assest/payments/vendor/ewallet/nine_pay.svg" },
  ],
  bank_transfer: [
    { id: "hncb_webatm", name_zh: "華南銀行", name_en: "HNCB WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/b33689e025cbab7616a437e35099a2d0ce418594/map/assest/payments/vendor/bank_transfer/hncb_webatm.svg" },
    { id: "ctbc_webatm", name_zh: "中國信託", name_en: "CTBC WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/ctbc_webatm.svg" },
    { id: "e_sun_webatm", name_zh: "玉山銀行", name_en: "E.SUN WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/053766572429f0c7d454c6fa9613e516d36c1330/map/assest/payments/vendor/bank_transfer/e_sun_webatm.svg" },
    { id: "taishin_webatm", name_zh: "台新銀行", name_en: "Taishin WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/taishin_webatm.svg" },
    { id: "tfb_webatm", name_zh: "台北富邦", name_en: "TFB WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/tfb_webatm.svg" },
    { id: "land_bank_webatm", name_zh: "土地銀行", name_en: "Land Bank WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/land_bank_webatm.svg" },
    { id: "scsb_webatm", name_zh: "上海銀行", name_en: "SCSB WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/scsb_webatm.svg" },
    { id: "bo_t_webatm", name_zh: "台灣銀行", name_en: "BoT WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/bo_t_webatm.svg" },
    { id: "mega_icbc_webatm", name_zh: "兆豐銀行", name_en: "Mega ICBC WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/mega_icbc_webatm.svg" },
    { id: "first_webatm", name_zh: "第一銀行", name_en: "First WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/first_webatm.svg" },
    { id: "chb_webatm", name_zh: "彰化銀行", name_en: "CHB WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/chb_webatm.svg" },
    { id: "postal_webatm", name_zh: "中華郵政", name_en: "POSTAL WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/postal_webatm.svg" },
    { id: "tcb_webatm", name_zh: "合作金庫", name_en: "TCB WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/038c738062661831d0835aa53c4d04b31cbfed5b/map/assest/payments/vendor/bank_transfer/tcb_webatm.svg" },
    { id: "icbc_atm_cn", name_zh: "工商銀行", name_en: "ICBC WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/icbc_atm_cn.svg" },
    { id: "abc_atm_cn", name_zh: "農業銀行", name_en: "ABC WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/abc_atm_cn.svg" },
    { id: "ccb_atm_cn", name_zh: "建設銀行", name_en: "CCB WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/ccb_atm_cn.svg" },
    { id: "boc_atm_cn", name_zh: "中國銀行", name_en: "BOC WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/boc_atm_cn.svg" },
    { id: "hsb_webatm_hk", name_zh: "恒生銀行", name_en: "HSB WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/hsb_webatm_hk.svg" },
    { id: "fps", name_zh: "轉數快", name_en: "FPS", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/fps.svg" },
    { id: "hsbc_webatm", name_zh: "上海滙豐銀行", name_en: "HSBC WebATM", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/HSBC_WebATM.svg" },
    { id: "bca", name_zh: "Bank Central Asia", name_en: "", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/bca.svg" },
    { id: "bni", name_zh: "Bank Negara Indonesia", name_en: "", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/bni.svg" },
    { id: "permata_bank", name_zh: "Permata Bank", name_en: "", icon: "./assest/payments/vendor/bank_transfer/permata_bank.svg" },
    { id: "cimb_clicks", name_zh: "CIMB Clicks", name_en: "", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/cimb_clicks.svg" },
    { id: "mandiri", name_zh: "Mandiri", name_en: "", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/mandiri.svg" },
    { id: "bri", name_zh: "Bank-Rakyat-Indonesia", name_en: "", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/bc5b0372e2c4109e1f222d6fc8958a7ff2d09dea/assest/payments/vendor/bank_transfer/bri.svg" },
    { id: "qris", name_zh: "QRIS", name_en: "QRIS", icon: "./assest/payments/vendor/bank_transfer/qris.svg" },
    { id: "bdo_network_bank", name_zh: "BDO 銀行", name_en: "BDO Bank", icon: "./assest/payments/vendor/bank_transfer/bdo_network_bank.png" },
    { id: "bank_of_commerce", name_zh: "Commerce 銀行", name_en: "Bank of Commerce", icon: "./assest/payments/vendor/bank_transfer/bank_of_commerce.png" },
    { id: "bpi", name_zh: "BPI 銀行", name_en: "BPI Online Bank", icon: "./assest/payments/vendor/bank_transfer/bpi.svg" },
    { id: "landbank", name_zh: "Landbank 銀行", name_en: "Landbank", icon: "./assest/payments/vendor/bank_transfer/landbank.svg" },
    { id: "chinabank", name_zh: "Chinabank 線上銀行", name_en: "Chinabank", icon: "./assest/payments/vendor/bank_transfer/chinabank.png" },
    { id: "rcbc", name_zh: "RCBC 銀行", name_en: "RCBC Bank", icon: "./assest/payments/vendor/bank_transfer/rcbc.png" },
    { id: "pnb", name_zh: "PNB 菲律賓國家銀行", name_en: "PNB Bank", icon: "./assest/payments/vendor/bank_transfer/pnb.png" },
    { id: "maybank", name_zh: "Maybank 馬來亞銀行", name_en: "Maybank", icon: "./assest/payments/vendor/bank_transfer/maybank.png" },
    { id: "security_bank", name_zh: "Security Bank 保安銀行", name_en: "Security Bank", icon: "./assest/payments/vendor/bank_transfer/security_bank.png" },
    { id: "unionbank", name_zh: "UnionBank 聯合銀行", name_en: "UnionBank", icon: "./assest/payments/vendor/bank_transfer/unionbank.svg" },
    { id: "ucpb", name_zh: "UCPB 國民聯合銀行", name_en: "UCPB Bank", icon: "./assest/payments/vendor/bank_transfer/ucpb.svg" },
    { id: "aub", name_zh: "AUB 菲律賓聯合銀行", name_en: "AUB Bank", icon: "./assest/payments/vendor/bank_transfer/aub.svg" },
    { id: "psbank", name_zh: "PSBank 菲律賓儲蓄銀行", name_en: "PS Bank", icon: "./assest/payments/vendor/bank_transfer/psbank.svg" },
    { id: "robinsons_bank", name_zh: "Robinsons Bank 羅賓森銀行", name_en: "Robinsons Bank", icon: "./assest/payments/vendor/bank_transfer/robinsons_bank.svg" },
    { id: "dbs", name_zh: "DBS 星展銀行", name_en: "DBS Bank", icon: "./assest/payments/vendor/bank_transfer/dbs.svg" },
    { id: "ocbc", name_zh: "OCBC 華僑銀行", name_en: "OCBC Bank", icon: "./assest/payments/vendor/bank_transfer/ocbc.svg" },
    { id: "uob", name_zh: "UOB 大華銀行", name_en: "UOB Bank", icon: "./assest/payments/vendor/bank_transfer/uob.svg" },
    { id: "standard_chartered", name_zh: "渣打銀行", name_en: "Standard Chartered Bank", icon: "./assest/payments/vendor/bank_transfer/standard_chartered.svg" },
    { id: "metrobank", name_zh: "Metrobank 大都會銀行", name_en: "Metrobank", icon: "./assest/payments/vendor/bank_transfer/metrobank.svg" },
    { id: "_dup_Metrobank_2", name_zh: "Metrobank 大都會銀行", name_en: "Metrobank", icon: "./assest/payments/vendor/bank_transfer/_dup_Metrobank_2.svg" },
    { id: "_dup_Metrobank_3", name_zh: "Metrobank 大都會銀行", name_en: "Metrobank", icon: "./assest/payments/vendor/bank_transfer/_dup_Metrobank_3.svg" },
    { id: "_placeholder_bank_transfer_1", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/bank_transfer/_placeholder_bank_transfer_1.svg" },
    { id: "cn_bank_transfer", name_zh: "大陸地區網銀支付", name_en: "CN Bank Transfer", icon: "./assest/payments/vendor/bank_transfer/cn_bank_transfer.svg" },
    { id: "aub_online_cash_payment", name_zh: "AUB OnlineCash Payment", name_en: "AUB OnlineCash Payment", icon: "./assest/payments/vendor/bank_transfer/aub_online_cash_payment.svg" },
    { id: "metrobank_otc_ph", name_zh: "Metrobank OTC", name_en: "Metrobank OTC", icon: "./assest/payments/vendor/bank_transfer/metrobank_otc_ph.svg" },
    { id: "robinson_s_bank_otc", name_zh: "Robinson's Bank OTC", name_en: "Robinson's Bank OTC", icon: "./assest/payments/vendor/bank_transfer/robinson_s_bank_otc.svg" },
    { id: "robinson_s_online", name_zh: "Robinson's Online", name_en: "Robinson's Online", icon: "./assest/payments/vendor/bank_transfer/robinson_s_online.svg" },
    { id: "fast", name_zh: "FAST", name_en: "FAST", icon: "./assest/payments/vendor/bank_transfer/fast.svg" },
    { id: "bangkok_bank", name_zh: "Bangkok bank", name_en: "Bangkok bank", icon: "./assest/payments/vendor/bank_transfer/bangkok_bank.svg" },
    { id: "k_plus", name_zh: "K-PLUS", name_en: "K-PLUS", icon: "./assest/payments/vendor/bank_transfer/k_plus.svg" },
    { id: "krung_thai_bank", name_zh: "Krung Thai bank", name_en: "Krung Thai bank", icon: "./assest/payments/vendor/bank_transfer/krung_thai_bank.svg" },
    { id: "krungsri_bank", name_zh: "Krungsri Bank", name_en: "Krungsri Bank", icon: "./assest/payments/vendor/bank_transfer/krungsri_bank.svg" },
    { id: "prompt_pay", name_zh: "PromptPay", name_en: "PromptPay", icon: "./assest/payments/vendor/bank_transfer/prompt_pay.svg" },
    { id: "qrpayment", name_zh: "QRpayment", name_en: "QRpayment", icon: "./assest/payments/vendor/bank_transfer/qrpayment.svg" },
    { id: "siam_commercial_bank", name_zh: "Siam Commercial Bank", name_en: "Siam Commercial Bank", icon: "./assest/payments/vendor/bank_transfer/siam_commercial_bank.svg" },
    { id: "thanachart_bank", name_zh: "Thanachart bank", name_en: "Thanachart bank", icon: "./assest/payments/vendor/bank_transfer/thanachart_bank.svg" },
    { id: "bank_transfer_brazil", name_zh: "銀行轉帳 (Brazil)", name_en: "Bank Transfer (Brazil)", icon: "./assest/payments/vendor/bank_transfer/bank_transfer_brazil.svg" },
    { id: "bank_transfer_colombia", name_zh: "銀行轉帳 (Colombia)", name_en: "Bank Transfer (Colombia)", icon: "./assest/payments/vendor/bank_transfer/bank_transfer_colombia.svg" },
    { id: "bank_transfer_chile", name_zh: "銀行轉帳 (Chile)", name_en: "Bank Transfer (Chile)", icon: "./assest/payments/vendor/bank_transfer/bank_transfer_chile.svg" },
    { id: "bank_transfer_peru", name_zh: "銀行轉帳 (Peru)", name_en: "Bank Transfer (Peru)", icon: "./assest/payments/vendor/bank_transfer/bank_transfer_peru.svg" },
    // 2026-07-06 依「資料付費廠簡易版20260706.xlsx」補齊 MY/VN 缺漏;SVG 待補,resolveIcon 會 fallback png/webp/jpg
    { id: "fpx", name_zh: "FPX", name_en: "FPX", icon: "./assest/payments/vendor/bank_transfer/fpx.svg" },
    { id: "atm_card_vietnam", name_zh: "ATM 卡 (Vietnam)", name_en: "ATM Card (Vietnam)", icon: "./assest/payments/vendor/bank_transfer/atm_card_vietnam.svg" },
    { id: "bank_transfer_vietnam", name_zh: "銀行轉帳 (Vietnam)", name_en: "Bank Transfer (Vietnam)", icon: "./assest/payments/vendor/bank_transfer/bank_transfer_vietnam.svg" },
  ],
  carrier_billing: [
    { id: "cht_mb", name_zh: "中華電信", name_en: "Chunghwa Telecom", icon: "./assest/payments/vendor/carrier_billing/cht_mb.svg" },
    { id: "fet_mb", name_zh: "遠傳電信", name_en: "FarEasTone", icon: "https://raw.githubusercontent.com/swdplat/Landing-Page/fdc277c1746691b225c360bf12886a8e83de2780/assest/payments/vendor/carrier_billing/FET_MB.svg" },
    { id: "twm_mb", name_zh: "台灣大哥大", name_en: "TaiwanMobile", icon: "./assest/payments/vendor/carrier_billing/twm_mb.svg" },
    { id: "_placeholder_carrier_billing_1", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/carrier_billing/_placeholder_carrier_billing_1.svg" },
    { id: "_placeholder_carrier_billing_2", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/carrier_billing/_placeholder_carrier_billing_2.svg" },
    { id: "_placeholder_carrier_billing_3", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/carrier_billing/_placeholder_carrier_billing_3.svg" },
    { id: "_placeholder_carrier_billing_4", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/carrier_billing/_placeholder_carrier_billing_4.svg" },
    { id: "_placeholder_carrier_billing_5", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/carrier_billing/_placeholder_carrier_billing_5.svg" },
    { id: "indosat", name_zh: "Indosat", name_en: "Indosat", icon: "./assest/payments/vendor/carrier_billing/indosat.svg" },
    { id: "three", name_zh: "Three", name_en: "Three", icon: "./assest/payments/vendor/carrier_billing/three.svg" },
    { id: "xl", name_zh: "XL", name_en: "XL", icon: "./assest/payments/vendor/carrier_billing/xl.svg" },
  ],
  cash_store: [
    { id: "seven_eleven_tw", name_zh: "7-11 統一超商", name_en: "7-ELEVEN", icon: "./assest/payments/vendor/cash_store/seven_eleven_tw.svg" },
    { id: "family_mart_tw", name_zh: "全家便利商店", name_en: "FamilyMart", icon: "./assest/payments/vendor/cash_store/family_mart_tw.svg" },
    { id: "hi_life_tw", name_zh: "萊爾富便利商店", name_en: "HiLIFE", icon: "./assest/payments/vendor/cash_store/hi_life_tw.svg" },
    { id: "ok_mart_tw", name_zh: "OK 超商", name_en: "OKMart", icon: "./assest/payments/vendor/cash_store/ok_mart_tw.svg" },
    { id: "alfamart", name_zh: "Alfa Group", name_en: "", icon: "./assest/payments/vendor/cash_store/alfamart.svg" },
    { id: "indomaret", name_zh: "Indomaret", name_en: "", icon: "./assest/payments/vendor/cash_store/indomaret.svg" },
    { id: "_placeholder_cash_store_1", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/cash_store/_placeholder_cash_store_1.svg" },
    { id: "_placeholder_cash_store_2", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/cash_store/_placeholder_cash_store_2.svg" },
    { id: "_placeholder_cash_store_3", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/cash_store/_placeholder_cash_store_3.svg" },
    { id: "_placeholder_cash_store_4", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/cash_store/_placeholder_cash_store_4.svg" },
    { id: "unnamed_tw_7", name_zh: "OK即時儲", name_en: "OK即時儲", icon: "./assest/payments/vendor/cash_store/unnamed_tw_7.svg" },
    { id: "seven_eleven_ph", name_zh: "7-ELEVEN", name_en: "7-ELEVEN", icon: "./assest/payments/vendor/cash_store/seven_eleven_ph.svg" },
    { id: "cebuana_bills_paymen", name_zh: "Cebuana Bills Paymen", name_en: "Cebuana Bills Paymen", icon: "./assest/payments/vendor/cash_store/cebuana_bills_paymen.svg" },
    { id: "ec_pay", name_zh: "EC Pay", name_en: "EC Pay", icon: "./assest/payments/vendor/cash_store/ec_pay.svg" },
    { id: "m_lhuillier", name_zh: "M.Lhuillier", name_en: "M.Lhuillier", icon: "./assest/payments/vendor/cash_store/m_lhuillier.svg" },
    { id: "palawan_pawnshop", name_zh: "PalawanPawnshop", name_en: "PalawanPawnshop", icon: "./assest/payments/vendor/cash_store/palawan_pawnshop.svg" },
    { id: "rd_pawnshop", name_zh: "RD Pawnshop", name_en: "RD Pawnshop", icon: "./assest/payments/vendor/cash_store/rd_pawnshop.svg" },
    { id: "robinsons_dept_store", name_zh: "Robinsons Dept Store", name_en: "Robinsons Dept Store", icon: "./assest/payments/vendor/cash_store/robinsons_dept_store.svg" },
    { id: "sm_retail", name_zh: "SM Retail", name_en: "SM Retail", icon: "./assest/payments/vendor/cash_store/sm_retail.svg" },
    { id: "so_cash", name_zh: "SoCash", name_en: "SoCash", icon: "./assest/payments/vendor/cash_store/so_cash.svg" },
    { id: "bigc", name_zh: "BIGC", name_en: "BIGC", icon: "./assest/payments/vendor/cash_store/bigc.svg" },
    { id: "cenpay", name_zh: "Cenpay", name_en: "Cenpay", icon: "./assest/payments/vendor/cash_store/cenpay.svg" },
    { id: "over_the_counter_brazil", name_zh: "實體商店繳費 (Brazil)", name_en: "Over the Counter (Brazil)", icon: "./assest/payments/vendor/cash_store/over_the_counter_brazil.svg" },
    { id: "over_the_counter_colombia", name_zh: "實體商店繳費 (Colombia)", name_en: "Over the Counter (Colombia)", icon: "./assest/payments/vendor/cash_store/over_the_counter_colombia.svg" },
    { id: "over_the_counter_chile", name_zh: "實體商店繳費 (Chile)", name_en: "Over the Counter (Chile)", icon: "./assest/payments/vendor/cash_store/over_the_counter_chile.svg" },
    { id: "over_the_counter_mexico", name_zh: "實體商店繳費 (Mexico)", name_en: "Over the Counter (Mexico)", icon: "./assest/payments/vendor/cash_store/over_the_counter_mexico.svg" },
    { id: "over_the_counter_peru", name_zh: "實體商店繳費 (Peru)", name_en: "Over the Counter (Peru)", icon: "./assest/payments/vendor/cash_store/over_the_counter_peru.svg" },
    { id: "over_the_counter_uruguay", name_zh: "實體商店繳費 (Uruguay)", name_en: "Over the Counter (Uruguay)", icon: "./assest/payments/vendor/cash_store/over_the_counter_uruguay.svg" },
  ],
  bnpl: [
    { id: "zingala", name_zh: "銀角零卡", name_en: "Zingala", icon: "./assest/payments/vendor/bnpl/zingala.png" },
    { id: "_placeholder_bnpl_1", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/bnpl/_placeholder_bnpl_1.svg" },
    { id: "_placeholder_bnpl_2", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/bnpl/_placeholder_bnpl_2.svg" },
    { id: "_placeholder_bnpl_3", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/bnpl/_placeholder_bnpl_3.svg" },
    { id: "_placeholder_bnpl_4", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/bnpl/_placeholder_bnpl_4.svg" },
    { id: "_placeholder_bnpl_5", name_zh: "填名字", name_en: "英文名稱", icon: "./assest/payments/vendor/bnpl/_placeholder_bnpl_5.svg" },
    { id: "aftee", name_zh: "AFTEE", name_en: "AFTEE", icon: "./assest/payments/vendor/bnpl/aftee.svg" },
  ],
  subscription: [
  ],
  reserved_2: [
  ],
};

// 掛載小工具:依路徑嘗試多副檔名(.svg → .png → .webp → .jpg)
window.resolveIcon = function(imgEl, baseOrFull){
  const isFull = /\/.+\.(svg|png|webp|jpg)$/i.test(baseOrFull);
  const bases  = isFull ? [baseOrFull.replace(/\.(svg|png|webp|jpg)$/i,'')] : [baseOrFull];
  const exts   = ['.svg', '.png', '.webp', '.jpg'];
  const tries  = [];
  bases.forEach(b => exts.forEach(ext => tries.push(b + ext)));
  let   i             = 0;
  const next          = ()=>{ if (i >= tries.length){ imgEl.removeAttribute('src'); imgEl.alt = 'No icon'; return; } imgEl.src = tries[i++]; };
        imgEl.onerror = next; next();
};
