// /country-info.js —— 自動生成（依 world.svg 標題鍵名對應）
window.COUNTRY_INFO = {
  "Andorra"                                 : { zhName: "安道尔", currencyCode: "EUR", currencyName: "欧元", iso2: "AD" },
  "United Arab Emirates"                    : { zhName: "阿拉伯联合酋长国", currencyCode: "AED", currencyName: "迪拉姆", iso2: "AE" },
  "Afghanistan"                             : { zhName: "阿富汗", currencyCode: "AFN", currencyName: "阿富汗尼", iso2: "AF" },
  "Antigua and Barbuda"                     : { zhName: "安提瓜和巴布达", currencyCode: "XCD", currencyName: "东加勒比元", iso2: "AG" },
  "Anguilla"                                : { zhName: "安圭拉", currencyCode: "XCD", currencyName: "东加勒比元", iso2: "AI" },
  "Albania"                                 : { zhName: "阿尔巴尼亚", currencyCode: "ALL", currencyName: "列克", iso2: "AL" },
  "Armenia"                                 : { zhName: "亚美尼亚", currencyCode: "AMD", currencyName: "德拉姆", iso2: "AM" },
  "Angola"                                  : { zhName: "安哥拉", currencyCode: "AOA", currencyName: "宽扎", iso2: "AO" },
  "Argentina"                               : { zhName: "阿根廷", currencyCode: "ARS", currencyName: "阿根廷披索", iso2: "AR" },
  "American Samoa"                          : { zhName: "美属萨摩亚", currencyCode: "USD", currencyName: "美元", iso2: "AS" },
  "Austria"                                 : { zhName: "奥地利", currencyCode: "EUR", currencyName: "欧元", iso2: "AT" },
  "Australia"                               : { zhName: "澳洲", currencyCode: "AUD", currencyName: "澳币", iso2: "AU" },
  "Aruba"                                   : { zhName: "阿鲁巴", currencyCode: "AWG", currencyName: "阿鲁巴弗罗林", iso2: "AW" },
  "Aland Islands"                           : { zhName: "奥兰群岛", currencyCode: "EUR", currencyName: "欧元", iso2: "AX" },
  "Azerbaijan"                              : { zhName: "亚塞拜然", currencyCode: "AZN", currencyName: "马纳特", iso2: "AZ" },
  "Bosnia and Herzegovina"                  : { zhName: "波士尼亚与赫塞哥维纳", currencyCode: "BAM", currencyName: "可兑换马克", iso2: "BA" },
  "Barbados"                                : { zhName: "巴贝多", currencyCode: "BBD", currencyName: "巴贝多元", iso2: "BB" },
  "Bangladesh"                              : { zhName: "孟加拉", currencyCode: "BDT", currencyName: "塔卡", iso2: "BD" },
  "Belgium"                                 : { zhName: "比利时", currencyCode: "EUR", currencyName: "欧元", iso2: "BE" },
  "Burkina Faso"                            : { zhName: "布吉纳法索", currencyCode: "XOF", currencyName: "西非法郎", iso2: "BF" },
  "Bulgaria"                                : { zhName: "保加利亚", currencyCode: "BGN", currencyName: "列弗", iso2: "BG" },
  "Bahrain"                                 : { zhName: "巴林", currencyCode: "BHD", currencyName: "巴林第纳尔", iso2: "BH" },
  "Burundi"                                 : { zhName: "蒲隆地", currencyCode: "BIF", currencyName: "蒲隆地法郎", iso2: "BI" },
  "Benin"                                   : { zhName: "贝南", currencyCode: "XOF", currencyName: "西非法郎", iso2: "BJ" },
  "Saint Barthelemy"                        : { zhName: "圣巴泰勒米", currencyCode: "EUR", currencyName: "欧元", iso2: "BL" },
  "Brunei Darussalam"                       : { zhName: "汶莱", currencyCode: "BND", currencyName: "汶莱元", iso2: "BN" },
  "Bolivia"                                 : { zhName: "玻利维亚", currencyCode: "BOB", currencyName: "玻利维亚诺", iso2: "BO" },
  "Bermuda"                                 : { zhName: "百慕达", currencyCode: "BMD", currencyName: "百慕达元", iso2: "BM" },
  "Bonaire,  Saint Eustachius and Saba"     : { zhName: "荷属加勒比（博奈尔/圣尤斯特歇/萨巴）", currencyCode: "USD", currencyName: "美元", iso2: "BQ" },
  "Brazil"                                  : { zhName: "巴西", currencyCode: "USD", currencyName: "美元", iso2: "BR" },
  "Bahamas"                                 : { zhName: "巴哈马", currencyCode: "BSD", currencyName: "巴哈马元", iso2: "BS" },
  "Bhutan"                                  : { zhName: "不丹", currencyCode: "BTN", currencyName: "努尔特鲁姆", iso2: "BT" },
  "Bouvet Island"                           : { zhName: "布威岛", currencyCode: "NOK", currencyName: "挪威克朗", iso2: "BV" },
  "Botswana"                                : { zhName: "波札那", currencyCode: "BWP", currencyName: "普拉", iso2: "BW" },
  "Belarus"                                 : { zhName: "白俄罗斯", currencyCode: "BYN", currencyName: "白俄卢布", iso2: "BY" },
  "Belize"                                  : { zhName: "贝里斯", currencyCode: "BZD", currencyName: "贝里斯元", iso2: "BZ" },
  "Canada"                                  : { zhName: "加拿大", currencyCode: "CAD", currencyName: "加币", iso2: "CA" },
  "Cocos  (Keeling)  Islands"               : { zhName: "科科斯（基林）群岛", currencyCode: "AUD", currencyName: "澳币", iso2: "CC" },
  "Democratic Republic of Congo"            : { zhName: "刚果民主共和国", currencyCode: "CDF", currencyName: "刚果法郎", iso2: "CD" },
  "Central African Republic"                : { zhName: "中非共和国", currencyCode: "XAF", currencyName: "中非法郎", iso2: "CF" },
  "Republic of Congo"                       : { zhName: "刚果共和国", currencyCode: "XAF", currencyName: "中非法郎", iso2: "CG" },
  "Switzerland"                             : { zhName: "瑞士", currencyCode: "CHF", currencyName: "瑞士法郎", iso2: "CH" },
  "Côte d'Ivoire"                           : { zhName: "象牙海岸", currencyCode: "XOF", currencyName: "西非法郎", iso2: "CI" },
  "Cook Islands"                            : { zhName: "库克群岛", currencyCode: "NZD", currencyName: "纽币", iso2: "CK" },
  "Chile"                                   : { zhName: "智利", currencyCode: "USD", currencyName: "美元", iso2: "CL" },
  "Cameroon"                                : { zhName: "喀麦隆", currencyCode: "XAF", currencyName: "中非法郎", iso2: "CM" },
  "China"                                   : { zhName: "中国", currencyCode: "CNY", currencyName: "人民币", iso2: "CN" },
  "Colombia"                                : { zhName: "哥伦比亚", currencyCode: "USD", currencyName: "美元", iso2: "CO" },
  "Costa Rica"                              : { zhName: "哥斯大黎加", currencyCode: "CRC", currencyName: "哥斯大黎加科隆", iso2: "CR" },
  "Cuba"                                    : { zhName: "古巴", currencyCode: "CUP", currencyName: "古巴披索", iso2: "CU" },
  "Cape Verde"                              : { zhName: "维德角", currencyCode: "CVE", currencyName: "埃斯库多", iso2: "CV" },
  "Curaçao"                                 : { zhName: "库拉索", currencyCode: "ANG", currencyName: "荷属安替列盾", iso2: "CW" },
  "Christmas Island"                        : { zhName: "圣诞岛", currencyCode: "AUD", currencyName: "澳币", iso2: "CX" },
  "Cyprus"                                  : { zhName: "赛普勒斯", currencyCode: "EUR", currencyName: "欧元", iso2: "CY" },
  "Czech Republic"                          : { zhName: "捷克", currencyCode: "CZK", currencyName: "捷克克朗", iso2: "CZ" },
  "Germany"                                 : { zhName: "德国", currencyCode: "EUR", currencyName: "欧元", iso2: "DE" },
  "Djibouti"                                : { zhName: "吉布地", currencyCode: "DJF", currencyName: "吉布地法郎", iso2: "DJ" },
  "Denmark"                                 : { zhName: "丹麦", currencyCode: "DKK", currencyName: "丹麦克朗", iso2: "DK" },
  "Dominica"                                : { zhName: "多明尼克", currencyCode: "XCD", currencyName: "东加勒比元", iso2: "DM" },
  "Dominican Republic"                      : { zhName: "多明尼加共和国", currencyCode: "DOP", currencyName: "多明尼加披索", iso2: "DO" },
  "Algeria"                                 : { zhName: "阿爾及利亞", currencyCode: "DZD", currencyName: "阿爾及利亞第納爾", iso2: "DZ" },
  "Ecuador"                                 : { zhName: "厄瓜多", currencyCode: "USD", currencyName: "美元", iso2: "EC" },
  "Egypt"                                   : { zhName: "埃及", currencyCode: "EGP", currencyName: "埃及鎊", iso2: "EG" },
  "Estonia"                                 : { zhName: "愛沙尼亞", currencyCode: "EUR", currencyName: "歐元", iso2: "EE" },
  "Western Sahara"                          : { zhName: "西撒哈拉", currencyCode: "MAD", currencyName: "摩洛哥迪拉姆", iso2: "EH" },
  "Eritrea"                                 : { zhName: "厄利垂亞", currencyCode: "ERN", currencyName: "納克法", iso2: "ER" },
  "Spain"                                   : { zhName: "西班牙", currencyCode: "EUR", currencyName: "歐元", iso2: "ES" },
  "Ethiopia"                                : { zhName: "衣索比亞", currencyCode: "ETB", currencyName: "比爾", iso2: "ET" },
  "Finland"                                 : { zhName: "芬蘭", currencyCode: "EUR", currencyName: "歐元", iso2: "FI" },
  "Fiji"                                    : { zhName: "斐濟", currencyCode: "FJD", currencyName: "斐濟元", iso2: "FJ" },
  "Falkland Islands"                        : { zhName: "福克蘭群島", currencyCode: "FKP", currencyName: "福克蘭鎊", iso2: "FK" },
  "Federated States of Micronesia"          : { zhName: "密克羅尼西亞聯邦", currencyCode: "USD", currencyName: "美元", iso2: "FM" },
  "Faroe Islands"                           : { zhName: "法羅群島", currencyCode: "DKK", currencyName: "丹麥克朗", iso2: "FO" },
  "France"                                  : { zhName: "法國", currencyCode: "EUR", currencyName: "歐元", iso2: "FR" },
  "Gabon"                                   : { zhName: "加彭", currencyCode: "XAF", currencyName: "中非法郎", iso2: "GA" },
  "United Kingdom"                          : { zhName: "英國", currencyCode: "GBP", currencyName: "英鎊", iso2: "GB" },
  "Georgia"                                 : { zhName: "喬治亞", currencyCode: "GEL", currencyName: "拉里", iso2: "GE" },
  "Grenada"                                 : { zhName: "格瑞那達", currencyCode: "XCD", currencyName: "東加勒比元", iso2: "GD" },
  "French Guiana"                           : { zhName: "法屬圭亞那", currencyCode: "EUR", currencyName: "歐元", iso2: "GF" },
  "Guernsey"                                : { zhName: "根西島", currencyCode: "GGP", currencyName: "根西鎊", iso2: "GG" },
  "Ghana"                                   : { zhName: "迦納", currencyCode: "GHS", currencyName: "塞地", iso2: "GH" },
  "Gibraltar"                               : { zhName: "直布羅陀", currencyCode: "GIP", currencyName: "直布羅陀鎊", iso2: "GI" },
  "Greenland"                               : { zhName: "格陵蘭", currencyCode: "DKK", currencyName: "丹麥克朗", iso2: "GL" },
  "Gambia"                                  : { zhName: "甘比亞", currencyCode: "GMD", currencyName: "達拉西", iso2: "GM" },
  "Guinea"                                  : { zhName: "幾內亞", currencyCode: "GNF", currencyName: "幾內亞法郎", iso2: "GN" },
  "Glorioso Islands"                        : { zhName: "格洛里奧索群島", currencyCode: "EUR", currencyName: "歐元", iso2: "TF-GO" },
  "Guadeloupe"                              : { zhName: "瓜地洛普", currencyCode: "EUR", currencyName: "歐元", iso2: "GP" },
  "Equatorial Guinea"                       : { zhName: "赤道幾內亞", currencyCode: "XAF", currencyName: "中非法郎", iso2: "GQ" },
  "Greece"                                  : { zhName: "希臘", currencyCode: "EUR", currencyName: "歐元", iso2: "GR" },
  "South Georgia and South Sandwich Islands": { zhName: "南喬治亞與南三明治群島", currencyCode: "GBP", currencyName: "英鎊", iso2: "GS" },
  "Guatemala"                               : { zhName: "瓜地馬拉", currencyCode: "GTQ", currencyName: "格查爾", iso2: "GT" },
  "Guam"                                    : { zhName: "關島", currencyCode: "USD", currencyName: "美元", iso2: "GU" },
  "Guinea-Bissau"                           : { zhName: "幾內亞比索", currencyCode: "XOF", currencyName: "西非法郎", iso2: "GW" },
  "Guyana"                                  : { zhName: "蓋亞那", currencyCode: "GYD", currencyName: "蓋亞那元", iso2: "GY" },
  "Hong Kong"                               : { zhName: "香港", currencyCode: "HKD", currencyName: "港幣", iso2: "HK" },
  "Heard Island and McDonald Islands"       : { zhName: "赫德島與麥當勞群島", currencyCode: "AUD", currencyName: "澳幣", iso2: "HM" },
  "Honduras"                                : { zhName: "宏都拉斯", currencyCode: "HNL", currencyName: "倫皮拉", iso2: "HN" },
  "Croatia"                                 : { zhName: "克羅埃西亞", currencyCode: "EUR", currencyName: "歐元", iso2: "HR" },
  "Haiti"                                   : { zhName: "海地", currencyCode: "HTG", currencyName: "古德", iso2: "HT" },
  "Hungary"                                 : { zhName: "匈牙利", currencyCode: "HUF", currencyName: "福林", iso2: "HU" },
  "Indonesia"                               : { zhName: "印尼", currencyCode: "IDR", currencyName: "印尼盾", iso2: "ID" },
  "Ireland"                                 : { zhName: "愛爾蘭", currencyCode: "EUR", currencyName: "歐元", iso2: "IE" },
  "Israel"                                  : { zhName: "以色列", currencyCode: "ILS", currencyName: "新謝克爾", iso2: "IL" },
  "Isle of Man"                             : { zhName: "曼島", currencyCode: "IMP", currencyName: "曼島鎊", iso2: "IM" },
  "India"                                   : { zhName: "印度", currencyCode: "INR", currencyName: "盧比", iso2: "IN" },
  "British Indian Ocean Territory"          : { zhName: "英屬印度洋領地", currencyCode: "USD", currencyName: "美元", iso2: "IO" },
  "Iraq"                                    : { zhName: "伊拉克", currencyCode: "IQD", currencyName: "伊拉克第納爾", iso2: "IQ" },
  "Iran"                                    : { zhName: "伊朗", currencyCode: "IRR", currencyName: "伊朗里亞爾", iso2: "IR" },
  "Iceland"                                 : { zhName: "冰島", currencyCode: "ISK", currencyName: "冰島克朗", iso2: "IS" },
  "Italy"                                   : { zhName: "義大利", currencyCode: "EUR", currencyName: "歐元", iso2: "IT" },
  "Jersey"                                  : { zhName: "澤西島", currencyCode: "JEP", currencyName: "澤西鎊", iso2: "JE" },
  "Jamaica"                                 : { zhName: "牙買加", currencyCode: "JMD", currencyName: "牙買加元", iso2: "JM" },
  "Jordan"                                  : { zhName: "約旦", currencyCode: "JOD", currencyName: "約旦第納爾", iso2: "JO" },
  "Japan"                                   : { zhName: "日本", currencyCode: "JPY", currencyName: "日圓", iso2: "JP" },
  "Juan De Nova Island"                     : { zhName: "胡安德諾瓦島", currencyCode: "EUR", currencyName: "歐元", iso2: "TF-JU" },
  "Kenya"                                   : { zhName: "肯亞", currencyCode: "KES", currencyName: "先令", iso2: "KE" },
  "Kyrgyzstan"                              : { zhName: "吉爾吉斯", currencyCode: "KGS", currencyName: "索姆", iso2: "KG" },
  "Cambodia"                                : { zhName: "柬埔寨", currencyCode: "KHR", currencyName: "瑞爾", iso2: "KH" },
  "Kiribati"                                : { zhName: "吉里巴斯", currencyCode: "AUD", currencyName: "澳幣", iso2: "KI" },
  "Comoros"                                 : { zhName: "科摩羅", currencyCode: "KMF", currencyName: "科摩羅法郎", iso2: "KM" },
  "Saint Kitts and Nevis"                   : { zhName: "聖克里斯多福及尼維斯", currencyCode: "XCD", currencyName: "東加勒比元", iso2: "KN" },
  "North Korea"                             : { zhName: "北韓", currencyCode: "KPW", currencyName: "朝鮮圓", iso2: "KP" },
  "South Korea"                             : { zhName: "南韓", currencyCode: "KRW", currencyName: "韓圓", iso2: "KR" },
  "Kosovo"                                  : { zhName: "科索沃", currencyCode: "EUR", currencyName: "歐元", iso2: "XK" },
  "Kuwait"                                  : { zhName: "科威特", currencyCode: "KWD", currencyName: "科威特第納爾", iso2: "KW" },
  "Cayman Islands"                          : { zhName: "開曼群島", currencyCode: "KYD", currencyName: "開曼元", iso2: "KY" },
  "Kazakhstan"                              : { zhName: "哈薩克", currencyCode: "KZT", currencyName: "堅戈", iso2: "KZ" },
  "Lao People's Democratic Republic"        : { zhName: "寮國", currencyCode: "LAK", currencyName: "基普", iso2: "LA" },
  "Lebanon"                                 : { zhName: "黎巴嫩", currencyCode: "LBP", currencyName: "黎巴嫩鎊", iso2: "LB" },
  "Saint Lucia"                             : { zhName: "聖露西亞", currencyCode: "XCD", currencyName: "東加勒比元", iso2: "LC" },
  "Liechtenstein"                           : { zhName: "列支敦斯登", currencyCode: "CHF", currencyName: "瑞士法郎", iso2: "LI" },
  "Sri Lanka"                               : { zhName: "斯里蘭卡", currencyCode: "LKR", currencyName: "盧比", iso2: "LK" },
  "Liberia"                                 : { zhName: "賴比瑞亞", currencyCode: "LRD", currencyName: "賴比瑞亞元", iso2: "LR" },
  "Lesotho"                                 : { zhName: "賴索托", currencyCode: "LSL", currencyName: "洛蒂", iso2: "LS" },
  "Lithuania"                               : { zhName: "立陶宛", currencyCode: "EUR", currencyName: "歐元", iso2: "LT" },
  "Luxembourg"                              : { zhName: "盧森堡", currencyCode: "EUR", currencyName: "歐元", iso2: "LU" },
  "Latvia"                                  : { zhName: "拉脫維亞", currencyCode: "EUR", currencyName: "歐元", iso2: "LV" },
  "Libya"                                   : { zhName: "利比亞", currencyCode: "LYD", currencyName: "第納爾", iso2: "LY" },
  "Morocco"                                 : { zhName: "摩洛哥", currencyCode: "MAD", currencyName: "迪拉姆", iso2: "MA" },
  "Monaco"                                  : { zhName: "摩納哥", currencyCode: "EUR", currencyName: "歐元", iso2: "MC" },
  "Moldova"                                 : { zhName: "摩爾多瓦", currencyCode: "MDL", currencyName: "列伊", iso2: "MD" },
  "Madagascar"                              : { zhName: "馬達加斯加", currencyCode: "MGA", currencyName: "阿里亞里", iso2: "MG" },
  "Montenegro"                              : { zhName: "蒙特內哥羅", currencyCode: "EUR", currencyName: "歐元", iso2: "ME" },
  "Saint Martin"                            : { zhName: "法屬聖馬丁", currencyCode: "EUR", currencyName: "歐元", iso2: "MF" },
  "Marshall Islands"                        : { zhName: "馬紹爾群島", currencyCode: "USD", currencyName: "美元", iso2: "MH" },
  "Macedonia"                               : { zhName: "北馬其頓", currencyCode: "MKD", currencyName: "第納爾", iso2: "MK" },
  "Mali"                                    : { zhName: "馬利", currencyCode: "XOF", currencyName: "西非法郎", iso2: "ML" },
  "Macau"                                   : { zhName: "澳門", currencyCode: "MOP", currencyName: "澳門幣", iso2: "MO" },
  "Myanmar"                                 : { zhName: "緬甸", currencyCode: "MMK", currencyName: "緬甸元", iso2: "MM" },
  "Mongolia"                                : { zhName: "蒙古", currencyCode: "MNT", currencyName: "圖格里克", iso2: "MN" },
  "Northern Mariana Islands"                : { zhName: "北馬利安納群島", currencyCode: "USD", currencyName: "美元", iso2: "MP" },
  "Martinique"                              : { zhName: "馬丁尼克", currencyCode: "EUR", currencyName: "歐元", iso2: "MQ" },
  "Mauritania"                              : { zhName: "茅利塔尼亞", currencyCode: "MRU", currencyName: "烏吉亞", iso2: "MR" },
  "Montserrat"                              : { zhName: "蒙特色拉特", currencyCode: "XCD", currencyName: "東加勒比元", iso2: "MS" },
  "Malta"                                   : { zhName: "馬爾他", currencyCode: "EUR", currencyName: "歐元", iso2: "MT" },
  "Mauritius"                               : { zhName: "模里西斯", currencyCode: "MUR", currencyName: "盧比", iso2: "MU" },
  "Maldives"                                : { zhName: "馬爾地夫", currencyCode: "MVR", currencyName: "拉菲亞", iso2: "MV" },
  "Malawi"                                  : { zhName: "馬拉威", currencyCode: "MWK", currencyName: "克瓦查", iso2: "MW" },
  "Mexico"                                  : { zhName: "墨西哥", currencyCode: "USD", currencyName: "美元", iso2: "MX" },
  "Malaysia"                                : { zhName: "馬來西亞", currencyCode: "MYR", currencyName: "令吉", iso2: "MY" },
  "Mozambique"                              : { zhName: "莫三比克", currencyCode: "MZN", currencyName: "梅蒂卡爾", iso2: "MZ" },
  "Namibia"                                 : { zhName: "納米比亞", currencyCode: "NAD", currencyName: "納米比亞元", iso2: "NA" },
  "New Caledonia"                           : { zhName: "新喀里多尼亞", currencyCode: "XPF", currencyName: "太平洋法郎", iso2: "NC" },
  "Niger"                                   : { zhName: "尼日", currencyCode: "XOF", currencyName: "西非法郎", iso2: "NE" },
  "Norfolk Island"                          : { zhName: "諾福克島", currencyCode: "AUD", currencyName: "澳幣", iso2: "NF" },
  "Nigeria"                                 : { zhName: "奈及利亞", currencyCode: "NGN", currencyName: "奈拉", iso2: "NG" },
  "Nicaragua"                               : { zhName: "尼加拉瓜", currencyCode: "NIO", currencyName: "金科多巴", iso2: "NI" },
  "Netherlands"                             : { zhName: "荷蘭", currencyCode: "EUR", currencyName: "歐元", iso2: "NL" },
  "Norway"                                  : { zhName: "挪威", currencyCode: "NOK", currencyName: "挪威克朗", iso2: "NO" },
  "Nepal"                                   : { zhName: "尼泊爾", currencyCode: "NPR", currencyName: "盧比", iso2: "NP" },
  "Nauru"                                   : { zhName: "諾魯", currencyCode: "AUD", currencyName: "澳幣", iso2: "NR" },
  "Niue"                                    : { zhName: "紐埃", currencyCode: "NZD", currencyName: "紐幣", iso2: "NU" },
  "New Zealand"                             : { zhName: "紐西蘭", currencyCode: "NZD", currencyName: "紐幣", iso2: "NZ" },
  "Oman"                                    : { zhName: "阿曼", currencyCode: "OMR", currencyName: "里亞爾", iso2: "OM" },
  "Panama"                                  : { zhName: "巴拿馬", currencyCode: "PAB", currencyName: "巴波亞", iso2: "PA" },
  "Peru"                                    : { zhName: "祕魯", currencyCode: "USD", currencyName: "美元", iso2: "PE" },
  "French Polynesia"                        : { zhName: "法屬玻里尼西亞", currencyCode: "XPF", currencyName: "太平洋法郎", iso2: "PF" },
  "Papua New Guinea"                        : { zhName: "巴布亞紐幾內亞", currencyCode: "PGK", currencyName: "基那", iso2: "PG" },
  "Philippines"                             : { zhName: "菲律賓", currencyCode: "PHP", currencyName: "披索", iso2: "PH" },
  "Pakistan"                                : { zhName: "巴基斯坦", currencyCode: "PKR", currencyName: "巴基斯坦盧比", iso2: "PK" },
  "Poland"                                  : { zhName: "波蘭", currencyCode: "PLN", currencyName: "茲羅提", iso2: "PL" },
  "Saint Pierre and Miquelon"               : { zhName: "聖皮耶與密克隆", currencyCode: "EUR", currencyName: "歐元", iso2: "PM" },
  "Pitcairn Islands"                        : { zhName: "皮特肯群島", currencyCode: "NZD", currencyName: "紐幣", iso2: "PN" },
  "Puerto Rico"                             : { zhName: "波多黎各", currencyCode: "USD", currencyName: "美元", iso2: "PR" },
  "Palestinian Territories"                 : { zhName: "巴勒斯坦", currencyCode: "ILS", currencyName: "新謝克爾", iso2: "PS" },
  "Portugal"                                : { zhName: "葡萄牙", currencyCode: "EUR", currencyName: "歐元", iso2: "PT" },
  "Palau"                                   : { zhName: "帛琉", currencyCode: "USD", currencyName: "美元", iso2: "PW" },
  "Paraguay"                                : { zhName: "巴拉圭", currencyCode: "PYG", currencyName: "瓜拉尼", iso2: "PY" },
  "Qatar"                                   : { zhName: "卡達", currencyCode: "QAR", currencyName: "卡達里亞爾", iso2: "QA" },
  "Reunion"                                 : { zhName: "留尼旺", currencyCode: "EUR", currencyName: "歐元", iso2: "RE" },
  "Romania"                                 : { zhName: "羅馬尼亞", currencyCode: "RON", currencyName: "列伊", iso2: "RO" },
  "Serbia"                                  : { zhName: "塞爾維亞", currencyCode: "RSD", currencyName: "第納爾", iso2: "RS" },
  "Russia"                                  : { zhName: "俄羅斯", currencyCode: "RUB", currencyName: "盧布", iso2: "RU" },
  "Rwanda"                                  : { zhName: "盧安達", currencyCode: "RWF", currencyName: "法郎", iso2: "RW" },
  "Saudi Arabia"                            : { zhName: "沙烏地阿拉伯", currencyCode: "SAR", currencyName: "里亞爾", iso2: "SA" },
  "Solomon Islands"                         : { zhName: "索羅門群島", currencyCode: "SBD", currencyName: "所羅門群島元", iso2: "SB" },
  "Seychelles"                              : { zhName: "塞席爾", currencyCode: "SCR", currencyName: "塞席爾盧比", iso2: "SC" },
  "Sudan"                                   : { zhName: "蘇丹", currencyCode: "SDG", currencyName: "蘇丹鎊", iso2: "SD" },
  "Sweden"                                  : { zhName: "瑞典", currencyCode: "SEK", currencyName: "瑞典克朗", iso2: "SE" },
  "Singapore"                               : { zhName: "新加坡", currencyCode: "SGD", currencyName: "新幣", iso2: "SG" },
  "Saint Helena"                            : { zhName: "聖赫勒拿", currencyCode: "SHP", currencyName: "聖赫勒拿鎊", iso2: "SH" },
  "Slovenia"                                : { zhName: "斯洛維尼亞", currencyCode: "EUR", currencyName: "歐元", iso2: "SI" },
  "Svalbard and Jan Mayen"                  : { zhName: "斯瓦巴及揚馬延", currencyCode: "NOK", currencyName: "挪威克朗", iso2: "SJ" },
  "Slovakia"                                : { zhName: "斯洛伐克", currencyCode: "EUR", currencyName: "歐元", iso2: "SK" },
  "Sierra Leone"                            : { zhName: "獅子山", currencyCode: "SLL", currencyName: "利昂", iso2: "SL" },
  "San Marino"                              : { zhName: "聖馬利諾", currencyCode: "EUR", currencyName: "歐元", iso2: "SM" },
  "Senegal"                                 : { zhName: "塞內加爾", currencyCode: "XOF", currencyName: "西非法郎", iso2: "SN" },
  "Somalia"                                 : { zhName: "索馬利亞", currencyCode: "SOS", currencyName: "索馬利亞先令", iso2: "SO" },
  "Suriname"                                : { zhName: "蘇利南", currencyCode: "SRD", currencyName: "蘇利南元", iso2: "SR" },
  "South Sudan"                             : { zhName: "南蘇丹", currencyCode: "SSP", currencyName: "南蘇丹鎊", iso2: "SS" },
  "Sao Tome and Principe"                   : { zhName: "聖多美普林西比", currencyCode: "STN", currencyName: "多布拉", iso2: "ST" },
  "El Salvador"                             : { zhName: "薩爾瓦多", currencyCode: "USD", currencyName: "美元", iso2: "SV" },
  "Sint Maarten"                            : { zhName: "荷屬聖馬丁", currencyCode: "ANG", currencyName: "荷屬安替列盾", iso2: "SX" },
  "Syria"                                   : { zhName: "敘利亞", currencyCode: "SYP", currencyName: "敘利亞鎊", iso2: "SY" },
  "Swaziland"                               : { zhName: "史瓦帝尼", currencyCode: "SZL", currencyName: "里蘭吉尼", iso2: "SZ" },
  "Turks and Caicos Islands"                : { zhName: "土克凱可群島", currencyCode: "USD", currencyName: "美元", iso2: "TC" },
  "Chad"                                    : { zhName: "查德", currencyCode: "XAF", currencyName: "中非法郎", iso2: "TD" },
  "French Southern and Antarctic Lands"     : { zhName: "法屬南部領地", currencyCode: "EUR", currencyName: "歐元", iso2: "TF" },
  "Togo"                                    : { zhName: "多哥", currencyCode: "XOF", currencyName: "西非法郎", iso2: "TG" },
  "Thailand"                                : { zhName: "泰國", currencyCode: "THB", currencyName: "泰銖", iso2: "TH" },
  "Tajikistan"                              : { zhName: "塔吉克", currencyCode: "TJS", currencyName: "索莫尼", iso2: "TJ" },
  "Tokelau"                                 : { zhName: "托克勞", currencyCode: "NZD", currencyName: "紐幣", iso2: "TK" },
  "Timor-Leste"                             : { zhName: "東帝汶", currencyCode: "USD", currencyName: "美元", iso2: "TL" },
  "Turkmenistan"                            : { zhName: "土庫曼", currencyCode: "TMT", currencyName: "馬納特", iso2: "TM" },
  "Tunisia"                                 : { zhName: "突尼西亞", currencyCode: "TND", currencyName: "突尼西亞第納爾", iso2: "TN" },
  "Tonga"                                   : { zhName: "東加", currencyCode: "TOP", currencyName: "潘加", iso2: "TO" },
  "Turkey"                                  : { zhName: "土耳其", currencyCode: "TRY", currencyName: "里拉", iso2: "TR" },
  "Trinidad and Tobago"                     : { zhName: "千里達及托巴哥", currencyCode: "TTD", currencyName: "千里達及托巴哥元", iso2: "TT" },
  "Tuvalu"                                  : { zhName: "吐瓦魯", currencyCode: "AUD", currencyName: "澳幣", iso2: "TV" },
  "Taiwan"                                  : { zhName: "台灣", currencyCode: "TWD", currencyName: "新台幣", iso2: "TW" },
  "Tanzania"                                : { zhName: "坦尚尼亞", currencyCode: "TZS", currencyName: "先令", iso2: "TZ" },
  "Ukraine"                                 : { zhName: "烏克蘭", currencyCode: "UAH", currencyName: "格里夫納", iso2: "UA" },
  "Uganda"                                  : { zhName: "烏干達", currencyCode: "UGX", currencyName: "先令", iso2: "UG" },
  "Jarvis Island"                           : { zhName: "賈維斯島", currencyCode: "USD", currencyName: "美元", iso2: "UM-DQ" },
  "Baker Island"                            : { zhName: "貝克島", currencyCode: "USD", currencyName: "美元", iso2: "UM-FQ" },
  "Howland Island"                          : { zhName: "豪蘭島", currencyCode: "USD", currencyName: "美元", iso2: "UM-HQ" },
  "Johnston Atoll"                          : { zhName: "約翰斯頓環礁", currencyCode: "USD", currencyName: "美元", iso2: "UM-JQ" },
  "Midway Islands"                          : { zhName: "中途島", currencyCode: "USD", currencyName: "美元", iso2: "UM-MQ" },
  "Wake Island"                             : { zhName: "威克島", currencyCode: "USD", currencyName: "美元", iso2: "UM-WQ" },
  "United States"                           : { zhName: "美國", currencyCode: "USD", currencyName: "美元", iso2: "US" },
  "Uruguay"                                 : { zhName: "烏拉圭", currencyCode: "USD", currencyName: "美金", iso2: "UY" },
  "Uzbekistan"                              : { zhName: "烏茲別克", currencyCode: "UZS", currencyName: "蘇姆", iso2: "UZ" },
  "Vatican City"                            : { zhName: "教廷（梵蒂岡）", currencyCode: "EUR", currencyName: "歐元", iso2: "VA" },
  "Saint Vincent and the Grenadines"        : { zhName: "聖文森及格瑞那丁", currencyCode: "XCD", currencyName: "東加勒比元", iso2: "VC" },
  "Venezuela"                               : { zhName: "委內瑞拉", currencyCode: "VES", currencyName: "玻利瓦爾", iso2: "VE" },
  "British Virgin Islands"                  : { zhName: "英屬維京群島", currencyCode: "USD", currencyName: "美元", iso2: "VG" },
  "US Virgin Islands"                       : { zhName: "美屬維京群島", currencyCode: "USD", currencyName: "美元", iso2: "VI" },
  "Vietnam"                                 : { zhName: "越南", currencyCode: "VND", currencyName: "越南盾", iso2: "VN" },
  "Vanuatu"                                 : { zhName: "萬那杜", currencyCode: "VUV", currencyName: "瓦圖", iso2: "VU" },
  "Wallis and Futuna"                       : { zhName: "瓦利斯和富圖那", currencyCode: "XPF", currencyName: "太平洋法郎", iso2: "WF" },
  "Samoa"                                   : { zhName: "薩摩亞", currencyCode: "WST", currencyName: "塔拉", iso2: "WS" },
  "Yemen"                                   : { zhName: "葉門", currencyCode: "YER", currencyName: "里亞爾", iso2: "YE" },
  "Mayotte"                                 : { zhName: "馬約特", currencyCode: "EUR", currencyName: "歐元", iso2: "YT" },
  "South Africa"                            : { zhName: "南非", currencyCode: "ZAR", currencyName: "蘭特", iso2: "ZA" },
  "Zambia"                                  : { zhName: "尚比亞", currencyCode: "ZMW", currencyName: "克瓦查", iso2: "ZM" },
  "Zimbabwe"                                : { zhName: "辛巴威", currencyCode: "ZWL", currencyName: "辛巴威元", iso2: "ZW" },
};

window.getCountryInfo = function(enName){
  const d = (window.COUNTRY_INFO && window.COUNTRY_INFO[enName]) || null;
  return d ? d: { zhName: enName, currencyCode: "—", currencyName: "—", iso2: null };
};